### ISSUE TITLE
Features and story

### ISSUE THREAD

**Issue by ernierasta** [Grokmoo/sulis#10]
Hi Jared!

First: I hope I am not too intrusive. I do not want to disturb development in any way, so feel free to turn me down - I will completely understand that.

I have few ideas, which I want to discuss.

1. **Stealth**. I love thieves in rpg-s. I have few ideas related to stealth:
a) **Real time stealth.** In Hale and current version of Sulis if thief is hidden and find enemy, game will automatically switch to combat mode. I think it would be much more convenient if it will happen only when thief is spotted.
b) **Direction awareness.** This one may hard to implement? Make NPC's much more perceptional in direction they are facing(maybe somehow make it obvious, which direction it is?). This would enable us to have scenes, where thief have to carefully plan a way to f.e. chest guarded by some NPC's. It would also enable possibility to make backstabbing more exciting (something like in Dragon Age Origins, when you have to position thief behind the enemy) Especially interesting when combined with following feature.
c) **NPC routes.** Ability to make scheduled routes. Maybe it is already possible with lua scripts? This would allow guards to move (or only turn right/left), but also make world more alive (wolves running in woods, people going to shop, ...).

2. **Ability to start as nobody, with no skills.** I personally find it very rewarding when game gives me opportunity to start as flimsy stupid character and allows me to find teachers and quests, that let me learn. In that scenario even having first ability is very exciting. But it just my opinion.

3. **Story.** You said (sourceforge), you want good story and believable world. As we all know - it is really hard to achieve. To craft this, a lot of time and attention to detail is needed. I personally think, that good stories are not told by intro's and 'cutscenes', but by NPC's them self. They IMHO should gradually introduce world to player giving him quests, somehow related to the "main" story or game world generally.
I do not know, how You see it, but maybe it is worth to consider more people involved in creating content. I know, that making own campaigns and mods would be quite easy in Sulis, but maybe it would be better to join forces and create one campaign, which would be awesome, with interesting story and quite deep lore? And maybe making this campain "never ending story" by always adding new content to it?
If you think that is good idea, it will require you to write down general story, so we can relate to it and create quests which will be unique to Sulis. I think that this story can be quite short, just tell us history of some part of your world, which races are there, who rules where, and what is current situation.
I am not sure if this should be publicly available though. While necessary  for creators, can spoil game for players. Maybe placing this document in doc directory  and placing warning on top would be enough?
If you think this is good idea, I have an idea to create a village, just bunch of buildings and people, but with hopefully interesting stories to tell and quests to solve. And by create I mean to create a script and then write down conversations. I can try to find tiles for it, but I am sure you have plans and vision how villages/towns should look in Your game, so I wont to interfere.

Sorry for so lengthy post. ;-)

**Comment by ernierasta** [comment]
Oh, and I forget about:

4. One inventory for all party. I find it much more convenient to use only one inventory for all characters. It remove tedious inventory micromanagement. Total inventory capacity can be sum of all party member capacities. If reason for separate inventory is immersion, then to exchange items characters should go to each other to give item to other party member. Just my opinion and it is not very important. Just to think about. ;-)

**Comment by Grokmoo** [comment]
Thanks, love your post and interest in the game!  My primary goal right now is to get to a workable prototype with primary systems all in place and a couple hour playable intro campaign.  I don't want to give dates but I do feel I am closing in on this goal.

1) Great ideas.  (a) and (c) I think are a must for Sulis.  They were technically difficult to implement in Hale due to some poor design decisions.  (b) I'm not sure about, but I don't want to discount it.  It is an interesting idea I haven't really thought of before.

2)  This is a cool idea and certainly will be possible to do via mods.  I want to add much more robust modding support - so you can have mods that are independent of a given campaign / module.  I am envisioning a separate mods menu that allows you to select or deselect from a list of installed mods when you start a game.
So, you could have a mod that changes the character progression system to accomplish this - it would be a great candidate to include in the base distribution of the game.

3) Having some sort of wiki or doc for overall story and lore is a great idea - and I would love to have a group of people working on this.  I honestly did not expect to see interest this early in the process - before I even have the initial prototype out.  I just need to find some time to do this.

4) Yes!  My current plan (which may evolve) is to have a small set of quick slots on each party member for useable items such as potions or changing weapons while in battle, and have a unified stash / party inventory for everything else.  I will have to play with it a bit and see how it feels.  This is on my short list of things needed for the initial prototype.

**Comment by ernierasta** [comment]
Thank you for great reply!
1. Great, very intrigued to see it. :-) b) is certainly not necessary for Sulis, but may bring something interesting into system (even mentioned DAO doesn't have directional perception, which is disappointing IMHO), we will see. :-)
2. Your idea of mods sounds great! If you expose enough, we can have Skyrim-like mod-ality. :-)
3. Yeah, I think, wiki would be good. In future also modders guides should be there. I am very interested in Sulis because of many reasons, but one of the most important is - there are no such open source games! Try to find even one similar game - maybe they are hidden from me somewhere, but I don't know any. There is Flare, but this is completely different beast. Great for sure, but I was never big Diablo fan, so while executed very well, not my taste until better story telling options are introduced. And second big one - Rust. I find Rust very intriguing, even I am not sure I will try to learn it soon - for many Rust beginners such engine must be dream comes true. It is brave message, that Rust is not only for system level programming. And did I express how amazed I am by engine itself? I think I do not. :-) So much nicer, then Hale. Zoom, transparency, ...
4. Great, it should work! In fact, in DA:O (sorry for comparing always to that game, but I think it is amazing one, with very good mechanics) there was no such system, but in practice it happens to me, that character dies only because I had no free spot on quick launch bar for particular healing potion size. And here little warning, i have not played to much of Hale (just cleared ork cave), but I never needed to use healing potion. Balance is the beast. :-)
 
I would write my ideas sooner, but I do not want to distract you from development. :-) And I will generally advice you to ignore me for now. :-D I have billion ideas, what can be done, how Sulic can become the best open source RPG ever. :-D But it will lead to never finish anything. Take your time, we waited for many years for project like that.

**Comment by Grokmoo** [comment]
Closing this out as I have created separate issues for (I believe) everything.
