### ISSUE TITLE
fonts are not embedded into executable

### ISSUE THREAD

**Issue by debris** [Grokmoo/sulis#132]
> os: macOS 10.14.3
rustc: rustc 1.39.0 (4560ea788 2019-11-04)
cargo 1.39.0 (1c6ec66d5 2019-09-30)
rev: latest master (7765f1dc4ff3cdf8170762558b873f90ff402439)

when running

```
cargo run --release
```

or

```
./target/release/main
```

sulis starts correctly, but if I try to start it differently

```
cd target/release
./main
```

it fails with

> Log is written to /Users/marek/.config/sulis/log/main.log
[2019-11-15 12:46:50.405093 +01:00] ERROR [src/bin/main.rs:66] Default font 'normal' is not defined.
[2019-11-15 12:46:50.405119 +01:00] ERROR [sulis_core/src/util.rs:363] Fatal error reading resources.
[2019-11-15 12:46:50.405134 +01:00] ERROR [sulis_core/src/util.rs:364] Exiting...

Not sure if this is an issue only with fonts or all assets

**Comment by Grokmoo** [comment]
This is by design - no assets are embedded in the executable in order to be maximally mod and custom content friendly.

To run the game with the main executable, there are two options I can think of:

1. copy the executable up two levels into the sulis directory (this is what the pre-built packaged releases do).
2. Edit your config.yml (in your ~/.config/.sulis) and make the three entries in the `resources` section all go up two levels, i.e. `../../data`.
