### ISSUE TITLE
Windowed display is bugged on Windows

### ISSUE THREAD

**Issue by metalwarrior665** [Grokmoo/sulis#183]
I have built it from source (rustc - 1.41.0) on Windows 10. The starting view is in a window and unfortunately, the icons are broken in the gameplay. For example I cannot cast a spell. 

After I switched to full-screen, everything works great.

**Comment by Grokmoo** [comment]
Hi, thanks for the report.  Unfortunately I'm not able to reproduce this behavior myself.

Can you provide more information:

- Contents of: `Documents\My Games\Sulis\log`
- Your hardware configuration - particularly graphics card.
- When you say full-screen mode, you mean Fullscreen, and not Borderless, correct?
- By the icons being broken - nothing displays correctly?  Can you provide a screenshot?

Thanks for your help.

**Comment by metalwarrior665** [comment]
I played with it and it seems a much weirder and broader problem with Windows and your game. The alteration of the screen resolution is not smooth and sometimes broken. Once it took a minute after quitting the game to get my screen back to normal resolution, in that run also full screen did not work properly.

- [main.log](https://github.com/Grokmoo/sulis/files/4664027/main.log)
- NVIDIA GeForce GTX 1050 Ti
- Yes
- 
![inventory](https://user-images.githubusercontent.com/29718487/82591775-23727e00-9ba0-11ea-8016-cb569cc460d8.png)
![broken window](https://user-images.githubusercontent.com/29718487/82591810-2ff6d680-9ba0-11ea-8b7e-e0ca1f1896aa.png)
![new game](https://user-images.githubusercontent.com/29718487/82591830-34bb8a80-9ba0-11ea-94e7-a57c43df0674.png)

**Comment by Grokmoo** [comment]
I am guessing these problems are related to the recent winit version upgrade.  I do have one more task to do on the current code to complete the upgrade - but I'm not sure it will solve your issues.

For what its worth, I am able to play on Windows 10 with very similar hardware and not encounter these issues. 

One more request if you get the chance - can you try launching the most recent released version and see if you see similar behavior:
https://github.com/Grokmoo/sulis/releases/download/0.5.0/sulis-0.5.0-win64.zip
This is only a few commits ago but does not have the winit version upgrade.  That should tell us whether the issue is due to the upgrade as I suspect.

**Comment by metalwarrior665** [comment]
No such issues on the release you just sent.

**Comment by Grokmoo** [comment]
Reverted to an older glium / winit for now.  Unfortunately using the new winit in the "correct" way will require a substantial chunk of work.  Its also not clear that it would even fix the problems.
